### ISSUE TITLE
Root mapping definition has unsupported parameters when creating monitor

### ISSUE THREAD

**Issue by dennyx** [opendistro-for-elasticsearch/alerting#103]
Hi,
I have a fresh installed cluster with Opendistro version: **1.1.0**
**Issue**:
When trying to create monitor in kibana alert panel, while could not found any data in UI, and check elasticsearch logs, get below errors.
Expected could successfully get data in create monitor page.
Appreciate if any kindly help, thanks.
`[2019-09-06T09:00:39,700][ERROR][c.a.o.a.MonitorRunner    ] [elasticcluster] Error loading alerts for monitor: _na_
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:394) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:476) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:152) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:392) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 15 more`
![image](https://user-images.githubusercontent.com/8176446/64416973-c5ae0c80-d0ca-11e9-9c41-78f8dd43a4f7.png)

**Comment by lucaswin-amzn** [comment]
Hi @dennyx,

Could you please share your alerting config mappings?

Please provide the output to the following commands:

1.
```
curl -X GET '<endpoint>/.opendistro-alerting-config/_mapping?pretty'
```

2.
```
curl -X GET '<endpoint>/.opendistro-alerting-alerts/_mapping?pretty'
```

**Comment by dennyx** [comment]
hi @lucaswin-amzn ,
Thanks for the kindly feedback.
**/.opendistro-alerting-config/_mapping?pretty** output as below:

[opendistro-alerting-config.output.txt](https://github.com/opendistro-for-elasticsearch/alerting/files/3791851/opendistro-alerting-config.output.txt)

**.opendistro-alerting-alerts/_mapping?pretty** output as below:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [.opendistro-alerting-alerts]",
        "resource.type" : "index_or_alias",
        "resource.id" : ".opendistro-alerting-alerts",
        "index_uuid" : "_na_",
        "index" : ".opendistro-alerting-alerts"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [.opendistro-alerting-alerts]",
    "resource.type" : "index_or_alias",
    "resource.id" : ".opendistro-alerting-alerts",
    "index_uuid" : "_na_",
    "index" : ".opendistro-alerting-alerts"
  },
  "status" : 404
}
```

Appreciate for the kindly help~

**Comment by mmiller1** [comment]
I'm also seeing this issue on a new 7.2 cluster.

**Comment by mmiller1** [comment]
Odd. I redeployed the cluster (using helm) with the exact same configuration and it is now working for me.

**Comment by vikram251186** [comment]
Hi,

I also have this error on my Elasticsearch node 7.2. Unable to resolve it.
Kindly help please.

**Comment by dennyx** [comment]
Temp work around for this issue, tested passed in my instance
A. manual delete **.opendistro-alerting-config** index.
B. run docker instance for elasticsearch&kibana locally, and get all alerting related indexes.
C. Create all alerting related indexes, keep the same with above 
1. .opendistro-alerting-alert-history-2020.02.06-1 (the day you config for this)
2. .opendistro-alerting-alerts
3. .opendistro-alerting-config

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/48
