### ISSUE TITLE
Creating custom_webhook throwing 500 internal error[BUG]

### ISSUE THREAD

**Issue by gitime** [opendistro-for-elasticsearch/alerting#316]
I have a slack webhook like below and its working fine both using REST client and curl;

`curl -X POST -k -i 'https://slack.com/api/chat.postMessage?token=test_token&channel=test_channel&text=sample_text'`

This request will publish message `sample_text` to my channel `test_channel` and can be viewed in slack app.

I tried below request from Kibana dev console;

```
POST _opendistro/_alerting/destinations
{
  "type": "custom_webhook",
  "name": "slack-destination",
  "custom_webhook": {
    "path": "api/chat.postMessage",
    "header_params": {
      "Content-Type": "application/json"
    },
    "scheme": "HTTPS",
    "port": 443,
    "query_params": {
      "token": "test_token",
      "channel": "test_channel",
      "text": "sample_text"
    },
    "host": "slack.com"
  }
}
```

when I tried this, i got 500 internal error;

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "alerting_exception",
        "reason" : "Connection refused"
      }
    ],
    "type" : "alerting_exception",
    "reason" : "Connection refused",
    "caused_by" : {
      "type" : "exception",
      "reason" : "java.net.ConnectException: Connection refused"
    }
  },
  "status" : 500
}
```

Below is the Kibana trace;

```
Alerting - DestinationService - createDestination: { Error: [alerting_exception] Connection refused
    at respond (/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/kibana/node_modules/lodash/lodash.js:4949:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 500,
  displayName: 'InternalServerError',
  message: '[alerting_exception] Connection refused',
  path: '/_opendistro/_alerting/destinations?refresh=wait_for',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'alerting_exception',
        reason: 'Connection refused',
        caused_by: [Object] },
     status: 500 },
  statusCode: 500,
  response:
   '{"error":{"root_cause":[{"type":"alerting_exception","reason":"Connection refused"}],"type":"alerting_exception","reason":"Connection refused","caused_by":{"type":"exception","reason":"java.net.ConnectException: Connection refused"}},"status":500}',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by franco-martin** [comment]
Im getting the same error when using kibana to create a simple monitor. 
Kibana log says 
`Alerting - MonitorService - createMonitor: { Error: [alerting_exception] Connection refused
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 500,
  displayName: 'InternalServerError',
  message: '[alerting_exception] Connection refused',
  path: '/_opendistro/_alerting/monitors?refresh=wait_for',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'alerting_exception',
        reason: 'Connection refused',
        caused_by: [Object] },
     status: 500 },
  statusCode: 500,
  response:
   '{"error":{"root_cause":[{"type":"alerting_exception","reason":"Connection refused"}],"type":"alerting_exception","reason":"Connection refused","caused_by":{"type":"exception","reason":"java.net.ConnectException: Connection refused"}},"status":500}',
  toString: [Function],
  toJSON: [Function] }
`

Elasticsearch log says
`
[2020-12-05T19:19:13,951][ERROR][c.a.o.a.u.AlertingException] [elastic0] Alerting error: java.net.ConnectException: Connection refused
[2020-12-05T19:19:13,951][WARN ][r.suppressed             ] [elastic0] path: /_opendistro/_alerting/monitors, params: {refresh=wait_for}
com.amazon.opendistroforelasticsearch.alerting.util.AlertingException: Connection refused
        at com.amazon.opendistroforelasticsearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:80) ~[opendistro_alerting-1.11.0.1.jar:1.11.0.1]
        at com.amazon.opendistroforelasticsearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$resolveUserAndStart$1.onFailure(TransportIndexMonitorAction.kt:196) [opendistro_alerting-1.11.0.1.jar:1.11.0.1]
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:617) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:375) [elasticsearch-rest-client-7.9.1.jar:7.9.1]
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62) [httpasyncclient-4.1.4.jar:4.1.4]        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.failed(PoolingNHttpClientConnectionManager.java:316) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) [httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:609) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:889) [httpcore-nio-4.4.12.jar:4.4.12]        at org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:176) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) [httpcore-nio-4.4.12.jar:4.4.12]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) [httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.4.jar:4.1.4]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.Exception: java.net.ConnectException: Connection refused
        ... 23 more
`

**Comment by franco-martin** [comment]
So it is possible to upload new monitors using the admin certificate, just not using kibana. 
@gitime would you mind trying that?

**Comment by RRadziejewski** [comment]
Same when creating a monitor with kibana :(

**Comment by gitime** [comment]
@franco-martin I am quite unsure about that, but honestly, what I am thinking now is to downgrade my stack to 1.9.0 sadly, because I have seen people reporting issues like this after upgrading to 1.10

**Comment by RRadziejewski** [comment]
My version is 7.9.1

**Comment by gitime** [comment]
@RRadziejewski sounds like i need to pick a vesion below that.. lol :D

**Comment by skkosuri-amzn** [comment]
https://opendistro.github.io/for-elasticsearch/blog/releases/2020/12/opendistro-1-12-0-released/ Is released. Please check it and let us know if this issue is present.

**Comment by skkosuri-amzn** [comment]
Feel free to re-open this, if you see the problem in 1.12 also.
