### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by enp** [opendistro-for-elasticsearch/alerting#322]
I'm trying to build plugin from source in centos:7 docker container:

```
yum -y update
yum install -y git-core java-11-openjdk-devel
yum clean all

export JAVA_HOME=/usr/lib/jvm/java/

cd /usr/src
git clone --depth 1 --branch v1.12.0.2 https://github.com/opendistro-for-elasticsearch/alerting.git
cd alerting
./gradlew build -DskipTests

```
Result of last command:

```
build-elasticsearch    | > Task :alerting:test
build-elasticsearch    | 
build-elasticsearch    | com.amazon.opendistroforelasticsearch.alerting.model.DestinationTests > classMethod FAILED
build-elasticsearch    |     java.lang.RuntimeException: can not run elasticsearch as root
build-elasticsearch    |         at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111)
build-elasticsearch    |         at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:86)
build-elasticsearch    |         at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:235)
build-elasticsearch    |         at java.base/java.lang.Class.forName0(Native Method)
build-elasticsearch    |         at java.base/java.lang.Class.forName(Class.java:398)
build-elasticsearch    |         at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
```

So, it looks as two bugs for me:

- Why tests are not skipped?
- Why elasticsearch can't start to test? Maybe some additional requirements not mentioned in docs must be satisfied (elasticsearch installed with binary in PATH or so for example)?

Or I'm doing something wrong and both issues described somewhere?

**Comment by skkosuri-amzn** [comment]
@enp To skip tests in gradle the format is `gradle build -x test`. For alerting, you could use `-x :alerting:integTestRunner -x :alerting:integTest`

On the exception `java.lang.RuntimeException: can not run elasticsearch as root` looks like you are running as root. Try the run as non-root user.
