### ISSUE TITLE
[BUG] Error: [alerting_exception] [10.xx.xx.xx][10.xx.xx.xx:9300][indices:admin/mapping/put]

### ISSUE THREAD

**Issue by linbingdouzhe** [opendistro-for-elasticsearch/alerting#338]
**Describe the bug**
failed to update or create monitor when migrate by remote reindex (1.3.0 -> 1.12.0)

**Other plugins installed**

**To Reproduce**
POST _reindex
{
"source": {
"remote": {
"host": "http://xxxxxx:xxx/",
"username": "xxx",
"password": "xxxxx"
},
"index": ".opendistro-alerting-config"

},
"dest": {
"index": ".opendistro-alerting-config"
}
}

and go "Alerting"  create or update any monitor
**Expected behavior**
everything normal

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
kibana logs:
```
","referer":"http://kibana-logcenter.awsnx.wisers.com.cn/app/opendistro-alerting"},"res":{"statusCode":200,"responseTime":90,"contentLength":9},"message":"GET /api/alerting/_settings 200 90ms - 9.0B"}
Alerting - DestinationService - createDestination: { Error: [alerting_exception] [10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 500,
  displayName: 'InternalServerError',
  message:
   '[alerting_exception] [10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]',
  path: '/_opendistro/_alerting/destinations?refresh=wait_for',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'alerting_exception',
        reason:
         '[10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]',
        caused_by: [Object] },
     status: 500 },
  statusCode: 500,
  response:
   '{"error":{"root_cause":[{"type":"alerting_exception","reason":"[10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]"}],"type":"alerting_exception","reason":"[10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]","caused_by":{"type":"exception","reason":"org.elasticsearch.transport.RemoteTransportException: [10.18.255.30][10.18.255.30:9300][indices:admin/mapping/put]"}},"status":500}',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by skkosuri-amzn** [comment]
Hi @linbingdouzhe  Monitors definitations are not compatable between 1.3 and  1.12 versions. One possible way you can try is: upgrade your 1.3 instance to 1.12 version or create the monitors again in 1.12.
