### ISSUE TITLE
Compatibility with Elastic 7.3

### ISSUE THREAD

**Issue by FrBillyD** [opendistro-for-elasticsearch/alerting#99]
Hello !
Can you make the plugin compatible with Elasticsearch 7.3.0 ?
I do not know what changes that bring about...

Thanks !!

**Comment by alen-z** [comment]
Can we expect 7.3.x (e.g. 7.3.1) support with this release? That would be great. Thank you.

**Comment by lucaswin-amzn** [comment]
Hi all, I have created the `opendistro-1.3` branch which is for ES `7.3.2`. While this release still has some ongoing testing to do, feel free to build it using `gradlew build` and install the zip.

Let me know if you have any issues with the plugin as a few things changed.

**Comment by alen-z** [comment]
Am I missing something?
```
bash-4.2$ bin/kibana-plugin install file://$(pwd)/test.zip 
Attempting to transfer from file:///usr/share/kibana/test.zip
Transferring 4051436 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```

**Comment by lucaswin-amzn** [comment]
Hi @alen-z, this repo is for the back end alerting plugin that needs to be installed in Elasticsearch. The front end repo can be found [here](https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin). I don't think they are ready for a 1.3 release yet, but hopefully soon!

In the mean time you can use the APIs provided by the back end to have full alerting functionality.

**Comment by alen-z** [comment]
Ow. Thank you. Will try this combination shortly. Feel free to close this. Keep up good work :)

**Comment by alen-z** [comment]
We are able to create alerts but they do not work. 

We have coordinator, master and data elasticsearch nodes. Is it ok to install plugin only on coordinator nodes which receive all our requests? Coordinator nodes are configured as ingest nodes.

What are we missing?

**Comment by qreshi** [comment]
Hey @alen-z, just a heads up, the Alerting Kibana plugin is available for 1.3 (ES 7.3.2) now. You can check the releases of the repo linked by @lucaswin-amzn above for the artifacts. Thanks for your patience!

**Comment by alen-z** [comment]
Added Elasticsearch plugin to all nodes, added proper Kibana plugin and `/_opendistro/_alerting/stats` returns multiple errors:
```json
{
   "_nodes":{
      "total":10,
      "successful":1,
      "failed":9,
      "failures":[
         {
            "type":"failed_node_exception",
            "reason":"Failed node [F5eUb9i_QFCc72T5agSVSQ]",
            "node_id":"F5eUb9i_QFCc72T5agSVSQ",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [7Urx3KHkQxWRnsRFw5bnfw]",
            "node_id":"7Urx3KHkQxWRnsRFw5bnfw",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [MEaWUkAyTNSN52l9UzDWug]",
            "node_id":"MEaWUkAyTNSN52l9UzDWug",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [jOlHL8FSTLCnGwdi0vNBBQ]",
            "node_id":"jOlHL8FSTLCnGwdi0vNBBQ",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [lZOVjHH3SqqkBfp4xaQU3g]",
            "node_id":"lZOVjHH3SqqkBfp4xaQU3g",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [z1NvTg1RTCCANiwP-GSzuQ]",
            "node_id":"z1NvTg1RTCCANiwP-GSzuQ",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [FSuHAubaSdy2bVEJjiWGow]",
            "node_id":"FSuHAubaSdy2bVEJjiWGow",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [3w5gVJsgRgC7tykruh_kgA]",
            "node_id":"3w5gVJsgRgC7tykruh_kgA",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         },
         {
            "type":"failed_node_exception",
            "reason":"Failed node [0SdtDkm6SWOHtipxcabwww]",
            "node_id":"0SdtDkm6SWOHtipxcabwww",
            "caused_by":{
               "type":"transport_serialization_exception",
               "reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
               "caused_by":{
                  "type":"illegal_state_exception",
                  "reason":"node must not be null"
               }
            }
         }
      ]
   },
   "cluster_name":"dummy",
   "opendistro.scheduled_jobs.enabled":true,
   "scheduled_job_index_exists":true,
   "scheduled_job_index_status":"green",
   "nodes_on_schedule":1,
   "nodes_not_on_schedule":0,
   "nodes":{
      "i920K2G5Qm-weamt7WyVGA":{
         "name":"coordinator-2",
         "schedule_status":"green",
         "roles":[
            "INGEST"
         ],
         "job_scheduling_metrics":{
            "last_full_sweep_time_millis":41917,
            "full_sweep_on_time":true
         },
         "jobs_info":{

         }
      }
   }
}
```
Any idea where we are stuck?

**Comment by alen-z** [comment]
Hi, we'd appreciate any input to previous post. Thank you for your time.

**Comment by qreshi** [comment]
Hi @alen-z, thanks for reporting this issue. We were able to reproduce it on our end and are currently looking into it. We will provide an update here once we have a better idea of what is causing this. Thank you for your patience.

**Comment by alen-z** [comment]
Thank you for quick response. Can't wait to install new release. Cheers.

**Comment by alen-z** [comment]
Great, now we have a healthy `/_opendistro/_alerting/stats` :) Next issue we are investigating is unauthorized call from `_system` user. After investigation, we'll open an issue if we do not find a clue on our end.

This is one of the data nodes:
```yaml
node.data: true
node.ingest: false
node.master: false
```

Stacktrace:
```
{"type": "server", "timestamp": "2019-12-14T09:46:49,906+0000", "level": "ERROR", "component": "c.a.o.a.MonitorRunner", "cluster.name": "...", "node.name": "data-5", "cluster.uuid": "DVzN1nRJRIyO2Kx3QCjSuw", "node.id": "7Urx3KHkQxWRnsRFw5bnfw",  "message": "Error loading alerts for monitor: crnEA28BsjfGg33QiwQJ" ,
"stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: action [indices:data/read/search] is unauthorized for user [_system]",
"at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:34) ~[?:?]",
"at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:576) ~[?:?]",
"at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:378) ~[?:?]",
"at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:183) ~[?:?]",
"at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:172) ~[?:?]",
"at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:158) ~[?:?]",
"at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$24(AuthenticationService.java:563) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:572) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$18(AuthenticationService.java:465) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:472) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:356) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$9(AuthenticationService.java:327) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:345) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$checkForApiKey$3(AuthenticationService.java:288) ~[?:?]",
"at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.xpack.security.authc.ApiKeyService.authenticateWithApiKeyIfPresent(ApiKeyService.java:356) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.checkForApiKey(AuthenticationService.java:269) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:252) ~[?:?]",
"at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:390) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:248) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$6(AuthenticationService.java:306) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:317) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:244) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:196) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:139) ~[?:?]",
"at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:155) ~[?:?]",
"at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:107) ~[?:?]",
"at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:525) ~[elasticsearch-7.3.2.jar:7.3.2]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner$loadCurrentAlerts$response$1.invoke(MonitorRunner.kt:324) ~[opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner$loadCurrentAlerts$response$1.invoke(MonitorRunner.kt:97) ~[opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at com.amazon.opendistroforelasticsearch.alerting.elasticapi.ElasticExtensionsKt.suspendUntil(ElasticExtensions.kt:146) ~[alerting-core-1.3.0.1.jar:?]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner.loadCurrentAlerts(MonitorRunner.kt:324) ~[opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner.runMonitor(MonitorRunner.kt:186) [opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner.runMonitor$default(MonitorRunner.kt:177) [opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner$runJob$1.invokeSuspend(MonitorRunner.kt:174) [opendistro_alerting-1.3.0.1.jar:1.3.0.1]",
"at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) [kotlin-stdlib-1.3.21.jar:1.3.21-release-158 (1.3.21)]",
"at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]"] }
```

**Comment by lucaswin-amzn** [comment]
@alen-z I see you are using xpack security plugin along with alerting. The integration between these two is not expected. We have however integrated with the opendistro security plugin if you would like to use that.

**Comment by alen-z** [comment]
Thx for heads up. I was able to learn that the hard way – by finding out about this after serious time investment in implementing and debugging the plugin but I'm willing to give it a try to make it work with xpack.

**Comment by alen-z** [comment]
Quick question: Does opendistro security plug-in clashes with xpack? Is it expected for alerting plug-in to work alongside xpack with opendistro plug-in installed? Thank you.

**Comment by OferE** [comment]
@alen-z  - any luck in overcoming this xpack/poen distro alerting plugin clash?

**Comment by balusarakesh** [comment]
@alen-z were you able to figure it out?

**Comment by balusarakesh** [comment]
this is what working for me
 - we use kibana and elasticsearch images from elastic
 - Dockerfile for kibana
 ```
 FROM docker.elastic.co/kibana/kibana:7.10.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/releases/download/v1.12.0.2/opendistro_alerting_kibana.zip --allow-root
 ```
  - Dockerfile for ES
  ```
  FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.0
RUN echo "y" | bin/elasticsearch-plugin install https://github.com/opendistro-for-elasticsearch/alerting/releases/download/v1.12.0.2/alerting.zip
COPY opendistro_security-1.12.0.0.zip /tmp/opendistro_security-1.12.0.0.zip
RUN echo "y" | bin/elasticsearch-plugin install file:///tmp/opendistro_security-1.12.0.0.zip
  ```
  - we disable xpack and opendistr security and we are able to see alerting
  ```
       - xpack.security.enabled=false
      - opendistro_security.disabled=true
  ```
